### ISSUE TITLE
about与tags页面无法正常显示

### ISSUE THREAD

**Issue by hizoubin** [ahonn/hexo-theme-even#1]
谢谢提供主题。按照README.md在 source 下创建 tags和about 文件夹，并在该目录下创建 index.md，无法正常显示这两个页面，求解
http://hizoubin.github.io/tags/
http://hizoubin.github.io/about/

**Comment by ahonn** [comment]
你用的是 apollo，不是我修改后的主题啊。原主题是没有 about 与 tabs 的。

**Comment by hizoubin** [comment]
我之前是用even的 然后无法创建后再改用了apollo

**Comment by ahonn** [comment]
报什么错误没有？




-------- 原始邮件 --------
发件人：hizoubin <notifications@github.com>
时间：周二 3月29日 16:41
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] about与tags页面无法正常显示 (#1)

**Comment by iLeyar** [comment]
似乎导航里不能添加自定义页面。

**Comment by ahonn** [comment]
@iLeyar  是添加博客内的自定义页面吗？博客里面的自定义页面可以直接在 source 目录下创建文件目录并添加 HTML 文件，然后在 _config.yml 中添加链接名与链接地址。站外链接的话，例如 github 就直接添加到 _config.yml 中就行了~

**Comment by iLeyar** [comment]
不知道为嘛，我本地测试，添加了然后一直转圈圈。例如我有一个页面为 links
路径为 source/links/index.md，也添加到 _config.yml 但是打不开，debug 飘出一大串错误。

**Comment by ahonn** [comment]
@iLeyar  添加到 _config.yml 应该是 links: /links/ 哦。方便贴 log 吗？

**Comment by iLeyar** [comment]
```
GET /img/iconfont/iconfont-twitter.png 200 0.434 ms - -
14:05:24.178 DEBUG Rendering post: links/index.html
Unhandled rejection TypeError: /home/leyar/ileyar_com/themes/even/layout/mixins/tags.jade:4
    2| mixin tags()
    3|     .tags
  > 4|         for tag in page.tags.toArray()
    5|             a(href=url_for(tag.path))
    6|                 = tag.name
    7| 

Cannot read property 'toArray' of undefined
    at Object.eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1352:24)
    at Object.jade_mixins.tags.jade_interp [as tags] (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1390:4)
    at eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1429:20)
    at eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1821:22)
    at res (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:219:38)
    at Hexo.jadeRenderer (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/lib/renderer.js:8:5)
    at Hexo.tryCatcher (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/leyar/ileyar_com/node_modules/hexo/lib/hexo/render.js:59:21
    at tryCatcher (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by iLeyar** [comment]
配置文件是这样：
```
menu:
        #  Home: /
  Archives: /archives/
  Links: /links/
  About: /about/
  Contact: /message-board/
  RSS: /atom.xml
```

**Comment by iLeyar** [comment]
这几个页面，只有 archives ，about， rss 是可以打开的。

**Comment by ahonn** [comment]
@iLeyar 这个错误我之前也遇到过..是 Jade 的 bug 好像..需要重新 npm install

**Comment by iLeyar** [comment]
@ahonn  额？是要重新安装一次么？ 
我刚试了下直接`npm install`，再重新打开，依旧不行。

**Comment by ahonn** [comment]
@iLeyar  如果你不需要文章底部的 Tags 的话，也可以删除  even/layout/post.jade 中的 

```
block tags
    include mixins/tags
    +tags()
```

或者我把我的 node_modules 发给你

**Comment by iLeyar** [comment]
我觉得可以添加一个 page layout～ 类似于 about 这样，就不需要删除 post 的 Tags 项了吧～

**Comment by ahonn** [comment]
@iLeyar 咦，说得对。等会就加。所以是ok了么？

**Comment by iLeyar** [comment]
@ahonn  我暂时给所有页面都添加了一个 layout:about ，这样就木有问题。

**Comment by ahonn** [comment]
@iLeyar 自己用都没发现什么 bug，那个 toArray() 的问题是 npm 的锅所以我也不好解决。
清明放假有时间我好好折腾折腾。感谢反馈~

**Comment by iLeyar** [comment]
@ahonn  你可以自己添加一个自定义页面测试。我看你博客的页面都是已经定义好的：）

**Comment by ahonn** [comment]
@iLeyar  突然明白为什么出错了..刚刚已经修复了。现在自定义页面不需要添加 layout

**Comment by iLeyar** [comment]
@ahonn 我试试～

**Comment by iLeyar** [comment]
@ahonn 在我这似乎依旧不行。

**Comment by ahonn** [comment]
@iLeyar 
![qq20160331-0](https://cloud.githubusercontent.com/assets/9718515/14180487/c4448534-f795-11e5-9c8f-8a062a63f0a2.png)
![qq20160331-1](https://cloud.githubusercontent.com/assets/9718515/14180483/c35145a4-f795-11e5-9ac4-647ece894a86.png)

我这没有问题，我无法知道是什么错了。麻烦给我报错信息~麻烦啦

**Comment by iLeyar** [comment]
```
15:17:09.165 DEBUG Rendering post: message-board/index.html
Unhandled rejection TypeError: /home/leyar/ileyar_com/themes/even/layout/mixins/tags.jade:4
    2| mixin tags()
    3|     .tags
  > 4|         for tag in page.tags.toArray()
    5|             a(href=url_for(tag.path))
    6|                 = tag.name
    7| 

Cannot read property 'toArray' of undefined
    at Object.eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1352:24)
    at Object.jade_mixins.tags.jade_interp [as tags] (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1390:4)
    at eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1429:20)
    at eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1821:22)
    at res (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:219:38)
    at Hexo.jadeRenderer (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/lib/renderer.js:8:5)
    at Hexo.tryCatcher (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/leyar/ileyar_com/node_modules/hexo/lib/hexo/render.js:59:21
    at tryCatcher (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
![image](https://cloud.githubusercontent.com/assets/4384122/14180730/f707ab12-f796-11e5-8bd5-8ffad53287b6.png)

**Comment by ahonn** [comment]
@iLeyar  你没有更新呀~我刚刚修改了这个了

**Comment by iLeyar** [comment]
@ahonn 
```
Unhandled rejection TypeError: /home/leyar/ileyar_com/themes/even/layout/partial/sidebar.jade:15
    13|       span.title Friends Link
    14|       ul.links
  > 15|         each link, name in config.friends
    16|           li.link-item
    17|             a(href="#{link}")!= name
    18| 

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:876:31)
    at eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:919:4)
    at eval (eval at <anonymous> (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1758:22)
    at res (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:219:38)
    at Hexo.jadeRenderer (/home/leyar/ileyar_com/node_modules/hexo-renderer-jade/lib/renderer.js:8:5)
    at Hexo.tryCatcher (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/leyar/ileyar_com/node_modules/hexo/lib/hexo/render.js:59:21
    at tryCatcher (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/leyar/ileyar_com/node_modules/hexo/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
额，竟然要把config 文件移除才能 pull 。。
现在更新完了直接首页打不开了。。

**Comment by ahonn** [comment]
@iLeyar  ..我特么真是sb..这个是sidebar中友链的，还在写当中..给push上去了..

把 layout/partial/layout.jade 中的第16行的 block social 注释掉..我好二

**Comment by ahonn** [comment]
@iLeyar 刚刚把晚上写的暂时不启用了..应该没问题了..我要去面壁..

**Comment by ahonn** [comment]
@iLeyar  另外..配置文件最好不要把老的直接覆盖刚 pull 更新的。因为我今天 push 了好多次..改了很多东西

**Comment by iLeyar** [comment]
@ahonn  我是先备份了才 pull，然后在还原的。 另外还有 font cdn 建议可以加一个 https 支持。 360 的貌似木有 https 支持，不过中科大的有。现在主题已经用上了，感觉，还不错哦：）

**Comment by ahonn** [comment]
那就好。。第一个用户应该是～哈哈哈。有什么意见多多反馈～




-------- 原始邮件 --------
发件人：Leyar <notifications@github.com>
时间：周五 4月1日 10:53
收件人：ahonn/hexo-theme-even <hexo-theme-even@noreply.github.com>
抄送：Jiang Yuexun <yuexunjiang@outlook.com>
主题：Re: [ahonn/hexo-theme-even] about与tags页面无法正常显示 (#1)

**Comment by iLeyar** [comment]
另外如果在修改内容我建议还是新起一个分支。等你修改完了合并再 push。。这样就不会一不小就 push 到 master 分支还正好被人 pull 下来了～

**Comment by iLeyar** [comment]
对了，还有个问题，就是你 README.md 里面的安装方法有点问题。 如果直接通过你那个方法 clone 下来的文件名是 hexo-theme-even 而不是 even, 在启用的时候主题名如果写 even 会出错。所以建议后面加一个 `even` 这样就会新建并 clone 到 even 文件夹里了。
没错，踩了那个坑的人就是我- -！

**Comment by ahonn** [comment]
这个我昨晚就打算新开个 dev 分支。。之前一直自己在用所以没有什么感觉。这几天我再把文档重新好好写写。感谢妹子的踩坑与支持～

**Comment by ahonn** [comment]
@iLeyar 第一个用户好鸡冻。最近打算搞第二个主题。到时也给提提意见呗
