### ISSUE TITLE
鼠标滚动时，目录不会固定在右上角

### ISSUE THREAD

**Issue by luckyBears** [ahonn/hexo-theme-even#118]
当文章过长时，滚动文章。目录不能固定在右上方的可见区域，不能跟随文章移动。能帮我看下是什么问题吗

**Comment by luckyBears** [comment]
jquery-3.1.1.min.js:2 jQuery.Deferred exception: Cannot read property 'top' of undefined TypeError: Cannot read property 'top' of undefined
    at Object.Even.toc (http://localhost:4000/js/src/even.js?v=2.2.x:55:42)
    at HTMLDocument.<anonymous> (http://localhost:4000/js/src/bootstrap.js?v=2.2.x:5:22)
    at j (http://localhost:4000/lib/jquery/jquery-3.1.1.min.js:2:29948)
    at k (http://localhost:4000/lib/jquery/jquery-3.1.1.min.js:2:30262) undefined
r.Deferred.exceptionHook @ jquery-3.1.1.min.js:2

**Comment by ahonn** [comment]
hexo server 的问题没有加载 JavaScript 脚本，hexo clean 之后重试就可以了。
