### ISSUE TITLE
出bug了

### ISSUE THREAD

**Issue by AriaLyy** [ahonn/hexo-theme-even#168]
```
E:\blog\hexo\node_modules\hexo-renderer-scss\node_modules\node-sass-magic-importer\dist\index.js:133
      if (!hasFilters && this.store[storeKey] && this.store[storeKey].includes(absoluteUrl)) {
                                                                      ^

TypeError: this.store[storeKey].includes is not a function
    at MagicImporter.isInStore (E:\blog\hexo\node_modules\hexo-renderer-scss\node_modules\node-sass-magic-importer\dist\index.js:133:71)
    at MagicImporter.resolveSync (E:\blog\hexo\node_modules\hexo-renderer-scss\node_modules\node-sass-magic-importer\dist\index.js:199:16)
    at Object.importer (E:\blog\hexo\node_modules\hexo-renderer-scss\node_modules\node-sass-magic-importer\dist\index.js:296:26)
    at options.importer (E:\blog\hexo\node_modules\hexo-renderer-scss\node_modules\node-sass\lib\index.js:331:31)

```

**Comment by ahonn** [comment]
重新安装 hexo-renderer-scss

**Comment by AriaLyy** [comment]
重装了也不行，还是一样的问题... 我的是win7系统

**Comment by ahonn** [comment]
删除 node_modules 重新 npm install

**Comment by AriaLyy** [comment]
还是一样的问题，不知道是不是hexo-renderer-scss版本导致的

**Comment by AriaLyy** [comment]
使用`npm install --save hexo-renderer-sass`这个命令安装可以了，而使用readme的那个命令不行...
