### ISSUE TITLE
TAG排板样式乱了

### ISSUE THREAD

**Issue by aimer1124** [ahonn/hexo-theme-even#27]
[http://aimer1124.github.io/tags/Testing/](http://aimer1124.github.io/tags/Testing/)
TAG中显示多行时，日期与标题会被换行

**Comment by ahonn** [comment]
这是因为当语言选择中文时，日期上会有 “月” “日”。宽度不够，之前忘记测试这个了。

谢谢啦~已经修复了~

**Comment by aimer1124** [comment]
刚更新了下，样式问题已经修复[http://aimer1124.github.io/archives/page/2/](http://aimer1124.github.io/archives/page/2/)，但在hexo g的时候，会报错

```
Unhandled rejection TypeError: /Users/yjshi/Downloads/All/Blog/themes/even/layout/partial/header.jade:7
    5| //- Navbar
    6| ul.nav
  > 7|   each link, name in theme.menu
    8|     li.nav-link
    9|       if is_home() && name == "Home"
    10|         a.active(href=link)

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/Users/yjshi/Downloads/All/Blog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:775:31)
    at eval (eval at <anonymous> (/Users/yjshi/Downloads/All/Blog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:978:4)
    at eval (eval at <anonymous> (/Users/yjshi/Downloads/All/Blog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1237:22)
    at res (/Users/yjshi/Downloads/All/Blog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:219:38)
    at Hexo.jadeRenderer (/Users/yjshi/Downloads/All/Blog/node_modules/hexo-renderer-jade/lib/renderer.js:8:5)
    at Hexo.tryCatcher (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/yjshi/Downloads/All/Blog/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/yjshi/Downloads/All/Blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

还有另外一个问题：标题被换行之后，缩进可以只显示一行或者只在标题的位置缩进么？

**Comment by ahonn** [comment]
现在文章标题除了文章内，其他地方标题过长都会自动省略后面的部分。后面会考虑加上标题 Hover 显示整个标题。

由于还没有测试，所以现在在 develop 这个分支下。晚上回去我再完善。

至于那个报错，很久之前也遇到过。请检查一下 `_config.yml` 中是否格式正确，注释掉 menu 中不需要的项。或者可以尝试重新 hexo init。

感谢反馈 ：）
