### ISSUE TITLE
访问时报错

### ISSUE THREAD

**Issue by jojoting** [ahonn/hexo-theme-even#28]
$hexo server然后访问网站的时候报错
依赖的模块都装了

错误：
Unhandled rejection TypeError: /Users/jojoting/jojoblog/themes/hexo-theme-even/layout/partial/header.jade:7
   5| //- Navbar
    6| ul.nav
  > 7|   each link, name in theme.menu
    8|     li.nav-link
    9|       if is_home() && name == "Home"
    10|         a.active(href=link)

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/Users/jojoting/jojoblog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:727:31)
    at eval (eval at <anonymous> (/Users/jojoting/jojoblog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:930:4)
    at eval (eval at <anonymous> (/Users/jojoting/jojoblog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:218:8), <anonymous>:1162:22)
    at res (/Users/jojoting/jojoblog/node_modules/hexo-renderer-jade/node_modules/jade/lib/index.js:219:38)
    at _compiled (/Users/jojoting/jojoblog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/jojoting/jojoblog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/jojoting/jojoblog/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/jojoting/jojoblog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/jojoting/jojoblog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/jojoting/jojoblog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:328:10)
    at resume_ (_stream_readable.js:708:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by ahonn** [comment]
是不是没有新建 `_config.yml` 文件？可以先看一下 [文档](https://github.com/ahonn/hexo-theme-even/blob/master/doc/doc_zh.md)

**Comment by jojoting** [comment]
谢谢，新建config文件解决了

**Comment by jojoting** [comment]
你好，我想问下代码高亮的代码语言怎么选择？
