### ISSUE TITLE
新版本theme属性不生效，以及Categories404

### ISSUE THREAD

**Issue by motcwang** [ahonn/hexo-theme-even#53]
theme属性 color 和 headerlink无效：
![image](https://cloud.githubusercontent.com/assets/3970143/19505856/d75bb9f6-95f8-11e6-8ac3-a30e97786443.png)

Categories直接404，而且不仅是新版本也一样。

**Comment by ahonn** [comment]
昨天也有人提到了这个问题，我在本地重新 init 两次，依然没有发现问题的所在。
我猜可能是 Hexo 版本的问题，请试一下 `hexo -v` 看看 Hexo 的版本是哪一个，我这边是3.2.2。

**Comment by motcwang** [comment]
我这边也是3.2.2，其他版本如下：
```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.5.0 darwin x64
http_parser: 2.7.0
node: 6.7.0
v8: 5.1.281.83
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2j
```
还有那个category一直都找不到页面。

**Comment by ahonn** [comment]
是否存在  `/source/categories/index.md` ? 如果没有的话需要 new page 一个，具体文档里有。然后配置文件中的路径也得正确，不然也是找不到。

**Comment by ahonn** [comment]
可否重新在本地 init 多一个博客，看一些 theme 的配置是不是依旧不行？

**Comment by motcwang** [comment]
额，初始化失败了
```
extends partial/layout include mixins/container include mixins/paginator block title title= config.title block container +home() block pagination +paginator('home')
```

**Comment by ahonn** [comment]
需要安装 `npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync`

**Comment by motcwang** [comment]
用3.2.2后，之前也发现了下面这个问题，debug时候下面这个插件总是load失败，知道是什么问题么？
```
ERROR Plugin load failed: hexo-renderer-scss
Error: dlopen(/Users/xxx/blog/test/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
	/Users/xxx/blog/test/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 1200688
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/blog/test/node_modules/node-sass/lib/index.js:23:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/xxx/blog/test/node_modules/hexo-renderer-scss/lib/renderer.js:1:76)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Users/xxx/blog/test/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/xxx/blog/test/node_modules/hexo-renderer-scss/index.js:1:81
    at /Users/xxx/blog/test/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/xxx/blog/test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xxx/blog/test/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/xxx/blog/test/node_modules/bluebird/js/release/promise.js:567:18)
```

**Comment by ahonn** [comment]
在博客跟目录下安装 `npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync`。README 有写，按照 README 来就可以了。

**Comment by motcwang** [comment]
嗯，就是按照README做的。刚才是因为我这node版本切换后的问题导致的。
我重新初始化了，theme好像还是不起作用。

**Comment by motcwang** [comment]
你的node版本是多少？我发现如果切换到6.7.0的时候在执行如下：
```
npm install --save hexo-renderer-jade hexo-renderer-scss hexo-generator-feed hexo-generator-sitemap hexo-browsersync
```
会有如下错误：
```
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/xxxx/.nvm/versions/node/v6.7.0/bin/node" "/Users/xxxx/.nvm/versions/node/v6.7.0/bin/npm" "install" "--save" "hexo-renderer-jade" "hexo-renderer-scss" "hexo-generator-feed" "hexo-generator-sitemap" "hexo-browsersync"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.10.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.10.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xxxx/blog/test/blog/npm-debug.log

```

**Comment by ahonn** [comment]
是node-sass安装失败了，手动单独安装 npm install node-sass

**Comment by motcwang** [comment]
主题可以使用了，我执行了clean之后就好了。
