### ISSUE TITLE
v2.0.0 版本更新信息

### ISSUE THREAD

**Issue by ahonn** [ahonn/hexo-theme-even#76]
## 更新信息
- 使用 swig 重写主题布局结构。
- 重构主题样式，将样式变量集中一个文件方便自定义。
- 移除 zepto，引入 jQuery。重写 JavaScript 脚本。
- 移除 iconfont 字体，使用 iconfont 在线字体。
- 修改文章上下页链接文字为文章标题，移动端不变。
- 增加站内搜索（需安装 `hexo-generator-search`）。
- 增加移动端顶部导航栏。

## TODO
- [x] 添加 Fancybox 支持
- [ ] 添加可选的代码高亮

**Comment by quentin-chen** [comment]
更新2.0之后，已经执行了 `hexo clean`。

```
Unhandled rejection TypeError: undefined is not a function
    at Object.urlForHelper (/Users/quentin/blog/node_modules/hexo/lib/plugins/helper/url_for.js:9:31)
    at Object.wrapper (/Users/quentin/blog/node_modules/hexo/node_modules/lodash/lodash.js:4962:19)
    at Object.feedTagHelper (/Users/quentin/blog/node_modules/hexo/lib/plugins/helper/feed_tag.js:8:48)
    at wrapper (/Users/quentin/blog/node_modules/hexo/node_modules/lodash/lodash.js:4962:19)
    at Object.eval [as tpl] (eval at <anonymous> (/Users/quentin/blog/node_modules/hexo/node_modules/swig/lib/swig.js:498:13), <anonymous>:60:123)
    at compiled (/Users/quentin/blog/node_modules/hexo/node_modules/swig/lib/swig.js:619:18)
    at Object.eval [as tpl] (eval at <anonymous> (/Users/quentin/blog/node_modules/hexo/node_modules/swig/lib/swig.js:498:13), <anonymous>:108:121)
    at compiled (/Users/quentin/blog/node_modules/hexo/node_modules/swig/lib/swig.js:619:18)
    at _compiled (/Users/quentin/blog/node_modules/hexo-inject/lib/patch/view.js:38:43)
    at View.render (/Users/quentin/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/quentin/blog/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/quentin/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:341:10)
    at resume_ (_stream_readable.js:725:12)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

**Comment by quentin-chen** [comment]
```
02:36:40.843 DEBUG Hexo version: 3.2.2
02:36:40.846 DEBUG Working directory: ~/blog/
02:36:40.972 DEBUG Config loaded: ~/blog/_config.yml
02:36:40.988 DEBUG Plugin loaded: hexo-baidu-url-submit
02:36:41.040 DEBUG Plugin loaded: hexo-browsersync
02:36:41.285 DEBUG Plugin loaded: hexo-deployer-git
02:36:41.291 DEBUG Plugin loaded: hexo-generator-archive
02:36:41.296 DEBUG Plugin loaded: hexo-generator-category
02:36:41.446 DEBUG Plugin loaded: hexo-generator-feed
02:36:41.451 DEBUG Plugin loaded: hexo-generator-index
02:36:41.536 DEBUG Plugin loaded: hexo-generator-seo-friendly-sitemap
02:36:41.542 DEBUG Plugin loaded: hexo-generator-sitemap
02:36:41.545 DEBUG Plugin loaded: hexo-generator-tag
02:36:41.601 INFO  [hexo-math] Using engine 'mathjax'
02:36:41.602 DEBUG Plugin loaded: hexo-math
02:36:41.876 INFO  [hexo-inject] installing hotfix for hexojs/hexo#1791
02:36:41.880 DEBUG Plugin loaded: hexo-inject
02:36:42.018 DEBUG Plugin loaded: hexo-reference
02:36:42.022 DEBUG Plugin loaded: hexo-renderer-ejs
02:36:42.311 DEBUG Plugin loaded: hexo-renderer-jade
02:36:42.407 DEBUG Plugin loaded: hexo-renderer-marked
02:36:42.409 DEBUG Plugin loaded: hexo-renderer-stylus
02:36:42.533 DEBUG Plugin loaded: hexo-server
02:36:42.545 DEBUG Plugin loaded: hexo-renderer-scss
02:36:42.671 DEBUG Plugin loaded: hexo-tag-aplayer
02:36:42.680 DEBUG Plugin loaded: hexo-tag-echarts3
02:36:42.967 DEBUG Plugin loaded: hexo-tag-owl
02:36:42.969 DEBUG [hexo-inject] firing inject_ready
02:36:43.403 DEBUG [hexo-inject] SKIP: undefined
02:36:43.404 DEBUG Incomplete document
Error: Incomplete document
    at Inject._transform (/Users/quentin/blog/node_modules/hexo-inject/lib/mixin/transform.js:29:34)
    at Hexo.tryCatcher (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/quentin/blog/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/quentin/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by yangg** [comment]
bootstrap 有什么作用？

**Comment by 11510746** [comment]
我也遇到了
`Error: Incomplete document
    at Inject._transform (/Users/quentin/blog/node_modules/hexo-inject/lib/mixin/transform.js:29:34)`问题，要怎么解决呢

**Comment by ahonn** [comment]
@11510746 请提供一下更多信息
